version: "3.8"
services:
  db:
    image: postgres:15.2
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - course_manager_network
  course_manager:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    env_file: .env
    volumes:
      - course_manager:/code
    networks:
      - course_manager_network
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - course_manager_network
    restart: unless-stopped
volumes:
  db:
  course_manager:

networks:
  course_manager_network:
    driver: bridge
